export interface ProjectBriefInput {
  title: string
  description: string
  apiName: string
  apiLink?: string
  apiDescription?: string
  createdAt?: string | Date
  feasibilityScore?: number
  originalityScore?: number
  filters?: {
    skillLevel: string
    stackFocus: string
    tone: string
    aiUsage: string
  }
}

export function slugify(title: string): string {
  const slug = title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")

  return slug || "project"
}

export function buildProjectBriefMarkdown({
  title,
  description,
  apiName,
  apiLink,
  apiDescription,
  createdAt,
  feasibilityScore,
  originalityScore,
  filters,
}: ProjectBriefInput): string {
  const date = (createdAt ? new Date(createdAt) : new Date()).toLocaleDateString()

  const sourceApiLines = [
    `- **API**: ${apiName}`,
    apiLink ? `- **Docs**: ${apiLink}` : null,
    apiDescription ? `- **About**: ${apiDescription}` : null,
  ].filter(Boolean)

  const sections = [
    `# ${title}`,
    `_Project brief generated by APIxplore on ${date} — paste this into Claude Code, Codex, or your coding agent of choice._`,
    `## Idea\n${description}`,
    `## Source API\n${sourceApiLines.join("\n")}`,
  ]

  if (filters) {
    sections.push(
      [
        "## Target profile",
        `- Skill level: ${filters.skillLevel}`,
        `- Stack focus: ${filters.stackFocus}`,
        `- Tone: ${filters.tone}`,
        `- AI usage: ${filters.aiUsage}`,
      ].join("\n")
    )
  }

  if (typeof feasibilityScore === "number" && typeof originalityScore === "number") {
    sections.push(
      [
        "## Feasibility & originality",
        `- Feasibility: ${feasibilityScore}/10`,
        `- Originality: ${originalityScore}/10`,
      ].join("\n")
    )
  }

  const apiRef = apiLink ? `${apiName} API (${apiLink})` : `${apiName} API`

  sections.push(
    [
      "## Kickoff prompt",
      `> I want to build "${title}" using the ${apiRef}. ${description}`,
      "> Please help me scaffold the project and build it step by step, starting with the core flow described above.",
    ].join("\n")
  )

  return sections.join("\n\n") + "\n"
}
